### ISSUE TITLE
追加する機能

### ISSUE THREAD

**Issue by hiroto0222** [RecursionGroupT/UzumakiDraw#1]

**Comment by strelitzia2692** [comment]
naruto

**Comment by sora-uzu** [comment]
### コンセプト
誰でも簡単に書ける自己紹介マップ

### 今回の概要に感じた課題、ニーズ
デザインやアピールが得意でないと、ゼロから描くのは難しい。
 - 何を書けば良いかわからない
 - 最大限アピールできる配置やデザインがわからない

↓

テンプレートやパーツをタイプ別で選べる感じでも良さそう
- 偏愛マップのタイプ
　- セパレート、吹き出し http://tamkaism.com/2014/06/henai-map/
　- マインドマップ https://sheage.jp/article/83843
　- 枠なし　https://cdn.discordapp.com/attachments/710030107611365418/1025567409597321257/unknown.png

### 機能
- Must: 文字とアイコンを配置できる。
　　　(アイコン挿入、文字入力、文字の太さ(3つ程度)、文字の色、フォント、大きさ、位置、枠、線)
- Want: デザインの幅を広げられる。出力できる。簡単にいい感じに作れる。
　　　(画像、動画、絵が書ける、imgの出力、テンプレ表示、テンプレごとのパーツ選択)
- Nice-to-have: MobileApp化(タッチペンに対応)、リリース、シェア機能、SNS化(フォロー、いいね、リスト分け)

**Comment by strelitzia2692** [comment]
コンセプト
・承認欲求を満たすような自己紹介マップ

偏愛マップの強み
・自由度の高さと個性が強く反映される

弱み
・作るハードルが高い
・名刺、履歴書、SNS、言葉での自己紹介などすでに自己紹介する方法がたくさんある

方向性
・名刺＋SNS＋ゲーミフィケーション

追加する機能のアイディア
・合計いいね数やフォロー数などによってスタンプやバッジなどが使えるようになる機能（差別化できるようにする）
・獲得物の全体ユーザーの所持率の表示

・共通の評価基準＋着実なステップアップ→いいデザインのマップを作る動機付与→フィードバック→...

**Comment by strelitzia2692** [comment]
- ログイン機能
- バッジ・スタンプ・フレーム機能
- SNS機能
- 一覧ページ（いいね、フォロー、ハッシュタグ、リスト分け）
- 作成ページ（チュートリアル・ツールボックス・KONVA）
  - チュートリアル：ユーザーにはパート・ジャンルごとに書いてもらい、最後にアプリ側で一枚絵にするイメージ。完成形のテンプレは最初に選べる。
  - Timer機能：パートごとに時間制限を設ける, 例gartic phone
- プロフィールページ
  - 編集機能

**Comment by strelitzia2692** [comment]
作成ページのタスク分解
~~１、konvaのキャンバスを作る~~
２、ツールボックス
~~ペンの筆のサイズ~~
~~筆の色~~
~~スタイルの変更（筆種類の選択）~~
・動画（GIF、アニメーションスタンプ）
・画像
・スタンプ/アイコン
・undo redo
・消しゴム機能
・文字入力
３、UI/UXデザイン

**Comment by hiroto0222** [comment]
作成（ゲーム機能）
1. 課題を表示
3. タイマー開始
4. ユーザーが絵を書く
5. 完了ボタンで次へ進む or タイマー終了で次へ進む
- canvas の保存
- canvas の clear 
6. 新しい課題を表示
